# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='achat',
  serialized_pb='\n\nchat.proto\x12\x05\x61\x63hat\"%\n\x04join\x12\x0f\n\x07\x63hannel\x18\x01 \x02(\t\x12\x0c\n\x04nick\x18\x02 \x02(\t\"\x17\n\x07message\x12\x0c\n\x04text\x18\x01 \x02(\t\"\x15\n\x05\x65rror\x12\x0c\n\x04text\x18\x01 \x02(\t')




_JOIN = _descriptor.Descriptor(
  name='join',
  full_name='achat.join',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='achat.join.channel', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick', full_name='achat.join.nick', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=58,
)


_MESSAGE = _descriptor.Descriptor(
  name='message',
  full_name='achat.message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='achat.message.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=60,
  serialized_end=83,
)


_ERROR = _descriptor.Descriptor(
  name='error',
  full_name='achat.error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='achat.error.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=85,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['join'] = _JOIN
DESCRIPTOR.message_types_by_name['message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['error'] = _ERROR

class join(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOIN

  # @@protoc_insertion_point(class_scope:achat.join)

class message(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGE

  # @@protoc_insertion_point(class_scope:achat.message)

class error(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ERROR

  # @@protoc_insertion_point(class_scope:achat.error)


# @@protoc_insertion_point(module_scope)
